/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2016-03-01 05:51:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class bindPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--1438065696992-->\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html ng-app=\"templateApp\" lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<link href=\"theme/resources/font-awesome/css/font-awesome.min.css\"\r\n");
      out.write("\ttype=\"text/css\" rel=\"stylesheet\"></link>\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"theme/resources/jqueryui-bootstrap/jquery-ui-1.9.2.custom.css\"\r\n");
      out.write("\ttype=\"text/css\" rel=\"stylesheet\"></link>\r\n");
      out.write("<link href=\"theme/resources/jqueryui-bootstrap/bootstrap.min.css\"\r\n");
      out.write("\ttype=\"text/css\" rel=\"stylesheet\"></link>\r\n");
      out.write("<link href=\"theme/resources/css/jquery.bootstrap.custom.css\"\r\n");
      out.write("\ttype=\"text/css\" rel=\"stylesheet\"></link>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"theme/resources/jqueryui-bootstrap/jquery-1.9.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"theme/resources/jqueryui-bootstrap/jquery-ui-1.9.2.custom.min.js\"></script>\r\n");
      out.write("<title>登录</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html;charset=UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body\r\n");
      out.write("\tstyle=\"padding-top: 10px; background-repeat: no-repeat; background-size: 100% auto\">\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction phoneDtp(val) {\r\n");
      out.write("\t\t\tvar phoneDiv = document.getElementById(\"phoneDiv\");\r\n");
      out.write("\t\t\tvar gudingDiv = document.getElementById(\"gudingDiv\");\r\n");
      out.write("\t\t\tif (val == 1) {\r\n");
      out.write("\t\t\t\tphoneDiv.style.display = \"none\";\r\n");
      out.write("\t\t\t\tgudingDiv.style.display = \"\";\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tphoneDiv.style.display = \"\";\r\n");
      out.write("\t\t\t\tgudingDiv.style.display = \"none\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar denant = 60;\r\n");
      out.write("\t\tvar InterVal;\r\n");
      out.write("\t\tfunction hourGlass() {\r\n");
      out.write("\t\t\tvar sends = document.getElementById(\"add\");\r\n");
      out.write("\t\t\tsends.setAttribute(\"disabled\", \"disabled\");\r\n");
      out.write("\t\t\tvar left = denant + \"s后重试\";\r\n");
      out.write("\t\t\tif (--denant > -1) {\r\n");
      out.write("\t\t\t\tsends.value = left;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\twindow.clearInterval(InterVal);//停止计时器\r\n");
      out.write("\t\t\t\tdenant = 60;\r\n");
      out.write("\t\t\t\t//改变button的值\r\n");
      out.write("\t\t\t\tsends.value = \"发送验证码\"\r\n");
      out.write("\t\t\t\t//设置button可以提交\r\n");
      out.write("\t\t\t\tsends.removeAttribute(\"disabled\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction phoneDtp(val) {\r\n");
      out.write("\t\t\tvar phoneDiv = document.getElementById(\"phoneDiv\");\r\n");
      out.write("\t\t\tvar gudingDiv = document.getElementById(\"gudingDiv\");\r\n");
      out.write("\t\t\tif (val == 1) {\r\n");
      out.write("\t\t\t\tphoneDiv.style.display = \"none\";\r\n");
      out.write("\t\t\t\tgudingDiv.style.display = \"\";\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tphoneDiv.style.display = \"\";\r\n");
      out.write("\t\t\t\tgudingDiv.style.display = \"none\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction regist(){\r\n");
      out.write("\t\t\tvar username = document.getElementById(\"username1\").value;\r\n");
      out.write("\t\t\tif(\"\" == username){\r\n");
      out.write("\t\t\t\talert(\"请输入您的姓名\");\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tmyform.submit();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction bind(){\r\n");
      out.write("\t\t\tvar username = document.getElementById(\"username\").value;\r\n");
      out.write("\t\t\tvar password = document.getElementById(\"password\").value;\r\n");
      out.write("\t\t\tif(username!=null&&password!=null&&username.length>=6&&username.length<=32&&password.length>=6&&password.length<=32){\r\n");
      out.write("\t\t\t\twindow.location=\"bindsuccess.jsp\";\r\n");
      out.write("\t\t\t}else if(username == \"\"){\r\n");
      out.write("\t\t\t\talert(\"请输入用户名\");\r\n");
      out.write("\t\t\t}else if(password == \"\"){\r\n");
      out.write("\t\t\t\talert(\"请输入密码\");\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\talert(\"用户名或密码错误！\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<div\r\n");
      out.write("\t\tstyle=\"background-color: #87CECB; width: 100%; height: 50px; margin-top: 4%; position: absolute; z-index: 2\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div style=\"margin-left: 5%; position: absolute; z-index: 3\">\r\n");
      out.write("\t\t<img style=\"height: 130px; width: 150px\" alt=\"绿洲\" src=\"img/head.bmp\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div style=\"margin-left: 9%; margin-top: 15%;\">\r\n");
      out.write("\t\t<font size=\"5px\" color=\"#87CECB\">恭喜您,[");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("]！差一步您就能成功登录绿洲！！</font>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div align=\"center\" style=\"float: right; margin-right: 5%;\">\r\n");
      out.write("\t\t<img src=\"img/xiaobei.bmp\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"container\"\r\n");
      out.write("\t\tstyle=\"margin-top: 3.5%; margin-left: 10%; width: 350px; height: 400px; border: 1px solid #A9A9A9;\">\r\n");
      out.write("\t\t<div id=\"phoneTgudingForm\"\r\n");
      out.write("\t\t\tclass=\"canvas-edited-text canvas-event-selectable canvas-event-draggable canvas-event-click canvas-event-dbclick ui-draggable ui-selectee ui-selected canvas-selected-border\"\r\n");
      out.write("\t\t\tdata-canvasrole=\"login-role-panel\" data-role=\"page\"\r\n");
      out.write("\t\t\tstyle=\"position: relative;\">\r\n");
      out.write("\t\t\t<div style=\"color: #87CECB;\">\r\n");
      out.write("\t\t\t\t<font size=\"6px\">完善信息</font>\r\n");
      out.write("\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<input id=\"loginBtn2\" value=\"跳过本步   >>\"\r\n");
      out.write("\t\t\t\t\tonclick=\"window.location='loginsuccess.jsp'\"\r\n");
      out.write("\t\t\t\t\tclass=\"canvas-edited-text btn btn-info\"\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 40%; background-color: #87CECB\" type=\"button\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"height: 10px\"></div>\r\n");
      out.write("\t\t\t<div id=\"phoneDiv\">\r\n");
      out.write("\t\t\t\t<form name=\"myform\"\r\n");
      out.write("\t\t\t\t\tclass=\"form-horizontal templatemo-container templatemo-login-form-1\"\r\n");
      out.write("\t\t\t\t\trole=\"form\" action=\"updateUsername\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"control-wrapper\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"username\" class=\"control-label fa-label\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-user\"></i></label> <input class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"username1\" name=\"username\" maxlength=\"32\" placeholder=\"您的姓名\" type=\"text\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<br /> <br /> <br />\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"control-wrapper\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"password\" class=\"control-label fa-label\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-user\"></i></label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t<input checked=\"checked\" name=\"sex\" type=\"radio\">&nbsp;<font\r\n");
      out.write("\t\t\t\t\t\t\t\tcolor=\"#87CECB\">男</font>\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"sex\" type=\"radio\">&nbsp;<font\r\n");
      out.write("\t\t\t\t\t\t\t\tcolor=\"#87CECB\">女</font>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<br /> <br /> <br />\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp; <input id=\"loginBtn2\" value=\"确认\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonclick=\"regist();\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"canvas-edited-text btn btn-info\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 100%; background-color: #87CECB\" type=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
