/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2016-02-26 01:03:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class bindsuccess_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--1438065696992-->\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html ng-app=\"templateApp\" lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<link href=\"theme/resources/font-awesome/css/font-awesome.min.css\"\r\n");
      out.write("\ttype=\"text/css\" rel=\"stylesheet\"></link>\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"theme/resources/jqueryui-bootstrap/jquery-ui-1.9.2.custom.css\"\r\n");
      out.write("\ttype=\"text/css\" rel=\"stylesheet\"></link>\r\n");
      out.write("<link href=\"theme/resources/jqueryui-bootstrap/bootstrap.min.css\"\r\n");
      out.write("\ttype=\"text/css\" rel=\"stylesheet\"></link>\r\n");
      out.write("<link href=\"theme/resources/css/jquery.bootstrap.custom.css\"\r\n");
      out.write("\ttype=\"text/css\" rel=\"stylesheet\"></link>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"theme/resources/jqueryui-bootstrap/jquery-1.9.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"theme/resources/jqueryui-bootstrap/jquery-ui-1.9.2.custom.min.js\"></script>\r\n");
      out.write("<title>登录</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html;charset=UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("<meta http-equiv=\"refresh\" content=\"3;url= loginsuccess.jsp \">\r\n");
      out.write("</head>\r\n");
      out.write("<body\r\n");
      out.write("\tstyle=\"padding-top: 10px; background-repeat: no-repeat; background-size: 100% auto\">\r\n");
      out.write("\t<script>\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<div\r\n");
      out.write("\t\tstyle=\"background-color: #87CECB; width: 100%; height: 50px; margin-top: 4%\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div style=\"float: left; margin-left: 12%; margin-top: 7%\">\r\n");
      out.write("\t\t<img style=\"height: 300px; width: 400px\" alt=\"绿洲\" src=\"img/logo.bmp\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div style=\"margin-top: 10%;\">\r\n");
      out.write("\t<font size=\"4px\" color=\"#87CECB\">恭喜您已成功绑定绿洲账号！\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t页面将跳转！\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t如果页面长时间未跳转\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t请<a href=\"loginsuccess.jsp\">单击此处</a></font>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
