/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2016-03-03 06:49:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class loginsucess_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>登录成功</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html;charset=UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("<style>\r\n");
      out.write("a{text-decoration:none}\r\n");
      out.write(".alsp{ font-family:\"楷体\";}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction updatename(){\r\n");
      out.write("\t\tvar name = prompt(\"请输入名字\");\r\n");
      out.write("\t\tvar oldname = document.getElementById(\"name\");\r\n");
      out.write("\t\tif(\"\" != name){\r\n");
      out.write("\t\t\toldname.value = name;\r\n");
      out.write("\t\t\talert(\"修改成功\");\r\n");
      out.write("\t\t\tmyform.submit();\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\talert(\"请输入名字\")\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction change(){\r\n");
      out.write("\t\tvar text = document.getElementById(\"text\");\r\n");
      out.write("\t\ttext.color='red';\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction change1(){\r\n");
      out.write("\t\tvar text = document.getElementById(\"text\");\r\n");
      out.write("\t\ttext.color='white';\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div\r\n");
      out.write("\tstyle=\"background-color: #87CECB; width: 100%; height: 50px;margin-top: 3%;position: absolute;z-index: 2\">\r\n");
      out.write("\t<div style=\"margin-left: 75% ; padding-top: 15px\">\r\n");
      out.write("\t\t<img alt=\"\" src=\"img/touxiang.png\">&nbsp;<a href=\"login.jsp\"><font size=\"2px\" color=\"white\">登录</font></a>&nbsp;<a href=\"regist.jsp\"><font size=\"2px\" color=\"white\">注册</font></a>\r\n");
      out.write("\t\t&nbsp;\r\n");
      out.write("\t\t<a href=\"/portal/qqLogin\"><img alt=\"\" src=\"img/qqlogin.png\">\r\n");
      out.write("\t\t<font size=\"2px\" color=\"white\">QQ登录</font></a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div style=\"margin-left: 5%;position: absolute;z-index: 3\"><img style=\"height: 130px; width: 150px\" alt=\"绿洲\" src=\"img/head.bmp\"></div>\r\n");
      out.write("<form action=\"updateUsername\" id=\"myform\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"username\" id=\"name\">\r\n");
      out.write("</form>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<div style=\"margin-top: 7%;width: 100%;\">\r\n");
      out.write("\t<img alt=\"\" src=\"img/main.bmp\">\r\n");
      out.write("\t<div align=\"left\" style=\"color: #87CECB;float: right;height: 500px;width: 550px;padding-top: 10%\">\r\n");
      out.write("\t<font size=\"5px\">恭喜！您已成功登录绿洲平台</font>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<div style=\"margin-right: 10%;height: 250px\" class=\"alsp\">\r\n");
      out.write("\t\t<font size=\"5px\">\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<img src=\"img/point.bmp\">云端大互联时代<br><br>\r\n");
      out.write("\t\t<img src=\"img/point.bmp\">多业务融合<br><br>\r\n");
      out.write("\t\t<img src=\"img/point.bmp\">让O2O变得更简单\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t</font>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- <div style=\"border: 1px solid #87CECB;height: 500px;width: 50%;\"></div> -->\r\n");
      out.write("<hr style=\"color: #87CECB;margin-top: 12%;\">\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("\t<p><font color=\"#87CECB\">&copy;2015 All Rights Reserved. &nbsp;&bull;&nbsp; Design by <a href=\"http://www.freecsstemplates.org/\">H3C</a> &nbsp;&bull;&nbsp; Icons by <a href=\"http://www.famfamfam.com/\">H3C</a>.</font></p>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
