/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2016-03-03 06:42:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--1438065696992-->\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html ng-app=\"templateApp\" lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<link href=\"theme/resources/font-awesome/css/font-awesome.min.css\"\n");
      out.write("\ttype=\"text/css\" rel=\"stylesheet\"></link>\n");
      out.write("<link\n");
      out.write("\thref=\"theme/resources/jqueryui-bootstrap/jquery-ui-1.9.2.custom.css\"\n");
      out.write("\ttype=\"text/css\" rel=\"stylesheet\"></link>\n");
      out.write("<link href=\"theme/resources/jqueryui-bootstrap/bootstrap.min.css\"\n");
      out.write("\ttype=\"text/css\" rel=\"stylesheet\"></link>\n");
      out.write("<link href=\"theme/resources/css/jquery.bootstrap.custom.css\"\n");
      out.write("\ttype=\"text/css\" rel=\"stylesheet\"></link>\n");
      out.write("<script type=\"text/javascript\"\n");
      out.write("\tsrc=\"theme/resources/jqueryui-bootstrap/jquery-1.9.0.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\"\n");
      out.write("\tsrc=\"theme/resources/jqueryui-bootstrap/jquery-ui-1.9.2.custom.min.js\"></script>\n");
      out.write("<title>登录</title>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html;charset=UTF-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body\n");
      out.write("\tstyle=\"padding-top: 10px; background-repeat: no-repeat; background-size: 100% auto\">\n");
      out.write("\t<script>\n");
      out.write("\t\tvar denant = 60;\n");
      out.write("\t\tvar InterVal;\n");
      out.write("\t\tfunction hourGlass() {\n");
      out.write("\t\t\tvar sends = document.getElementById(\"add\");\n");
      out.write("\t\t\tsends.setAttribute(\"disabled\", \"disabled\");\n");
      out.write("\t\t\tvar left = denant + \"s后重试\";\n");
      out.write("\t\t\tif (--denant > -1) {\n");
      out.write("\t\t\t\tsends.value = left;\n");
      out.write("\t\t\t} else {\n");
      out.write("\t\t\t\twindow.clearInterval(InterVal);//停止计时器\n");
      out.write("\t\t\t\tdenant = 60;\n");
      out.write("\t\t\t\t//改变button的值\n");
      out.write("\t\t\t\tsends.value = \"发送验证码\"\n");
      out.write("\t\t\t\t//设置button可以提交\n");
      out.write("\t\t\t\tsends.removeAttribute(\"disabled\");\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t\tfunction isSendSUCC(sm) {\n");
      out.write("\t\t\tvar phones = document.getElementById(\"phone\");\n");
      out.write("\t\t\tvar phoneValue = phones.value;\n");
      out.write("\t\t\tvar phonepattenString = /^1[3|4|5|7|8][0-9]{9}$/;\n");
      out.write("\t\t\tif (phoneValue != null && \"\" != phoneValue) {\n");
      out.write("\t\t\t\tif (phoneValue.length == 11) {\n");
      out.write("\t\t\t\t\t//alert(\"kk1\");\n");
      out.write("\t\t\t\t\tif (phonepattenString.test(phoneValue)) {\n");
      out.write("\t\t\t\t\t\tvar sendBtn = document.getElementById(\"add\");\n");
      out.write("\t\t\t\t\t\tsendBtn.removeAttribute(\"disabled\");\n");
      out.write("\t\t\t\t\t\tsendBtn.value = \"正在发送...\";\n");
      out.write("\t\t\t\t\t\tsendBtn.style.color = \"white\";\n");
      out.write("\t\t\t\t\t\tsendBtn.style.fontSize = \"14px\";\n");
      out.write("\t\t\t\t\t\tsendBtn.setAttribute(\"disabled\", \"disabled\");\n");
      out.write("\t\t\t\t\t\t//短信是否发送成功\n");
      out.write("\t\t\t\t\t\tif (sm) {\n");
      out.write("\t\t\t\t\t\t\tno = \"\";\n");
      out.write("\t\t\t\t\t\t\tInterVal = window.setInterval(hourGlass, 1000);\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t} else {\n");
      out.write("\t\t\t\t\t\talert('手机号格式错误');\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t} else {\n");
      out.write("\t\t\t\t\talert('手机号格式错误');\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t} else {\n");
      out.write("\t\t\t\talert('请输入手机号');\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t\tfunction phoneDtp(val) {\n");
      out.write("\t\t\tvar phoneDiv = document.getElementById(\"phoneDiv\");\n");
      out.write("\t\t\tvar gudingDiv = document.getElementById(\"gudingDiv\");\n");
      out.write("\t\t\tif (val == 1) {\n");
      out.write("\t\t\t\tphoneDiv.style.display = \"none\";\n");
      out.write("\t\t\t\tgudingDiv.style.display = \"\";\n");
      out.write("\t\t\t} else {\n");
      out.write("\t\t\t\tphoneDiv.style.display = \"\";\n");
      out.write("\t\t\t\tgudingDiv.style.display = \"none\";\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t\tfunction checkLogin() {\n");
      out.write("\t\t\tvar phones = document.getElementById(\"phone\");\n");
      out.write("\t\t\tvar code = document.getElementById(\"password2\").value;\n");
      out.write("\t\t\tvar phoneValue = phones.value;\n");
      out.write("\t\t\tvar phonepattenString = /^1[3|4|5|7|8][0-9]{9}$/;\n");
      out.write("\t\t\tif(null == phoneValue||phoneValue==\"\"){\n");
      out.write("\t\t\t\talert(\"请输入手机号\");\n");
      out.write("\t\t\t}else if(!phonepattenString.test(phoneValue)){\n");
      out.write("\t\t\t\talert(\"请输入正确的手机号\");\n");
      out.write("\t\t\t}else if(code != null && code.length == 4){\n");
      out.write("\t\t\t\twindow.location = \"loginsuccess.jsp\";\n");
      out.write("\t\t\t}else{\n");
      out.write("\t\t\t\talert(\"请输入正确的验证码\");\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t\tfunction login(){\n");
      out.write("\t\t\tvar username = document.getElementById(\"username1\").value;\n");
      out.write("\t\t\tvar password = document.getElementById(\"password1\").value;\n");
      out.write("\t\t\talert(\"用户名或密码错误！\");\n");
      out.write("\t\t}\n");
      out.write("\t</script>\n");
      out.write("\t<div\n");
      out.write("\t\tstyle=\"background-color: #87CECB; width: 100%; height: 50px; margin-top: 3%;z-index: 2;position: absolute;\">\n");
      out.write("\t</div>\n");
      out.write("\t<div style=\"margin-left: 5%;position: absolute;z-index: 3\"><img style=\"height: 130px; width: 150px\" alt=\"绿洲\" src=\"img/head.bmp\"></div>\n");
      out.write("\t<div style=\"float: left; margin-left: 12%; margin-top: 13%\">\n");
      out.write("\t\t<img style=\"height: 400px; width: 500px\" alt=\"绿洲\" src=\"img/leftlogo.bmp\">\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"container\"\n");
      out.write("\t\tstyle=\"padding-top: 10px; position: absolute; top: 200px; right: 200px; width: 350px; height: 500px;\">\n");
      out.write("\t\t<div id=\"phoneTgudingForm\"\n");
      out.write("\t\t\tclass=\"canvas-edited-text canvas-event-selectable canvas-event-draggable canvas-event-click canvas-event-dbclick ui-draggable ui-selectee ui-selected canvas-selected-border\"\n");
      out.write("\t\t\tdata-canvasrole=\"login-role-panel\" data-role=\"page\"\n");
      out.write("\t\t\tstyle=\"position: relative;\">\n");
      out.write("\t\t\t<div style=\"color: #87CECB;\">\n");
      out.write("\t\t\t\t<font size=\"6px\">登录绿洲</font>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a\n");
      out.write("\t\t\t\t\thref=\"forgetpsw.jsp\">忘记密码?</a>&nbsp;|&nbsp;<a href=\"regist.jsp\">用户注册</a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div style=\"height: 10px\"></div>\n");
      out.write("\t\t\t<div id=\"phoneDiv\">\n");
      out.write("\t\t\t\t<form\n");
      out.write("\t\t\t\t\tclass=\"form-horizontal templatemo-container templatemo-login-form-1\"\n");
      out.write("\t\t\t\t\trole=\"form\" action=\"#\" method=\"post\">\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-12\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"control-wrapper\">\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"username\" class=\"control-label fa-label\"><i\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-user\"></i></label> <input class=\"form-control\"\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"username1\" maxlength=\"32\" placeholder=\"用户名\" type=\"text\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-12\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"control-wrapper\">\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"password\" class=\"control-label fa-label\"><i\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-lock\"></i></label> <input class=\"form-control\"\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"password1\" maxlength=\"32\" placeholder=\"密码\" type=\"password\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:void(0)\" onclick=\"login();\"> <input id=\"loginBtn1\" value=\"登录\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"canvas-edited-text btn btn-info\"\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 100%; background-color: #87CECB\" type=\"button\">\n");
      out.write("\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div id=\"gudingDiv\" style=\"display: none;\">\n");
      out.write("\t\t\t\t<form\n");
      out.write("\t\t\t\t\tclass=\"form-horizontal templatemo-container templatemo-login-form-1\"\n");
      out.write("\t\t\t\t\trole=\"form\" action=\"#\" method=\"post\">\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-12\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"control-wrapper\">\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"username\" class=\"control-label fa-label\"><i\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-user\"></i></label> <input class=\"form-control\" id=\"phone\"\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"手机号\" type=\"text\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-8\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"control-wrapper\">\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"password\" class=\"control-label fa-label\"><i\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-lock\"></i></label> <input class=\"form-control\"\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"password2\" placeholder=\"验证码\" type=\"text\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<label style=\"font-size: 16px; color: red; margin-top: 2%\"\n");
      out.write("\t\t\t\t\t\t\tid=\"phoneTip1\"></label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-4\" style=\"padding-left: 0px;\">\n");
      out.write("\t\t\t\t\t\t\t<input id=\"add\" value=\"发送验证码\"\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 100%; background-color: #87CECB\"\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"canvas-edited-text btn btn-info\"\n");
      out.write("\t\t\t\t\t\t\t\tonclick=\"isSendSUCC(true)\" type=\"button\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-12\">\n");
      out.write("\t\t\t\t\t\t\t<input id=\"loginBtn2\" value=\"登录\" onclick=\"checkLogin();\"\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"canvas-edited-text btn btn-info\"\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 100%; background-color: #87CECB\" type=\"button\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-12\">\n");
      out.write("\t\t\t\t\t\t\t<a id=\"phoneDtp\" onclick=\"phoneDtp(2);\" href=\"#\">用户名登录 </a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div id=\"gudingForm\" style=\"display: none;\"\n");
      out.write("\t\t\tclass=\"canvas-edited-text canvas-event-selectable canvas-event-draggable canvas-event-click canvas-event-dbclick ui-draggable ui-selectee\"\n");
      out.write("\t\t\tdata-canvasrole=\"login-role-panel\" data-role=\"page\">\n");
      out.write("\t\t\t<form\n");
      out.write("\t\t\t\tclass=\"form-horizontal templatemo-container templatemo-login-form-1\"\n");
      out.write("\t\t\t\trole=\"form\" action=\"#\" method=\"post\">\n");
      out.write("\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-12\">\n");
      out.write("\t\t\t\t\t\t<div class=\"control-wrapper\">\n");
      out.write("\t\t\t\t\t\t\t<label for=\"username\" class=\"control-label fa-label\"><i\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-user\"></i></label> <input class=\"form-control\"\n");
      out.write("\t\t\t\t\t\t\t\tid=\"username3\" placeholder=\"用户名\" type=\"text\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-12\">\n");
      out.write("\t\t\t\t\t\t<div class=\"control-wrapper\">\n");
      out.write("\t\t\t\t\t\t\t<label for=\"password\" class=\"control-label fa-label\"><i\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-lock\"></i></label> <input class=\"form-control\"\n");
      out.write("\t\t\t\t\t\t\t\tid=\"password3\" placeholder=\"密码\" type=\"password\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t<input id=\"loginBtn3\" value=\"登录\"\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 100%; background-color: #87CECB;\" type=\"button\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div id=\"phoneForm\" style=\"display: none;\"\n");
      out.write("\t\t\tclass=\"canvas-edited-text canvas-event-selectable canvas-event-draggable canvas-event-click canvas-event-dbclick ui-draggable ui-selectee\"\n");
      out.write("\t\t\tdata-canvasrole=\"login-role-panel\" data-role=\"page\">\n");
      out.write("\t\t\t<form\n");
      out.write("\t\t\t\tclass=\"form-horizontal templatemo-container templatemo-login-form-1\"\n");
      out.write("\t\t\t\trole=\"form\" action=\"#\" method=\"post\">\n");
      out.write("\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-12\">\n");
      out.write("\t\t\t\t\t\t<div class=\"control-wrapper\">\n");
      out.write("\t\t\t\t\t\t\t<label for=\"username\" class=\"control-label fa-label\"><i\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-user\"></i></label> <input class=\"form-control\"\n");
      out.write("\t\t\t\t\t\t\t\tid=\"username4\" placeholder=\"用户名\" type=\"text\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-8\">\n");
      out.write("\t\t\t\t\t\t<div class=\"control-wrapper\">\n");
      out.write("\t\t\t\t\t\t\t<label for=\"password\" class=\"control-label fa-label\"><i\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-lock\"></i></label> <input class=\"form-control\"\n");
      out.write("\t\t\t\t\t\t\t\tid=\"password4\" placeholder=\"验证码\" type=\"text\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-4\" style=\"padding-left: 0px;\">\n");
      out.write("\t\t\t\t\t\t<input id=\"sendLoginMessageBtn4\" value=\"Get Code\"\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 100%;\" class=\"canvas-edited-text btn btn-info\"\n");
      out.write("\t\t\t\t\t\t\ttype=\"button\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-12\">\n");
      out.write("\t\t\t\t\t\t<input id=\"loginBtn4\" value=\"Login\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"canvas-edited-text btn btn-info\" style=\"width: 100%;\"\n");
      out.write("\t\t\t\t\t\t\ttype=\"button\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t<font size=\"2px\" color=\"#A9A9A9\">合作账户登录：</font> <a id=\"qq\"\n");
      out.write("\t\t\t\t\t\t\thref=\"/portal/qqLogin\"> <img src=\"img/qq1.png\"\n");
      out.write("\t\t\t\t\t\t\tstyle=\"margin-top: 3px; cursor: pointer\">\n");
      out.write("\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
